export const EVENT_CATEGORY = {
  music_and_concerts: {
    subcategories: [
      "pop",
      "rock",
      "jazz",
      "blues",
      "electronic/edm",
      "classical",
      "hip_hop/rap",
      "r&b/soul",
      "country/folk",
      "reggae/ska",
      "indie/alternative",
      "metal/punk",
      "k-pop/j-pop",
      "world/ethnic",
      "experimental/avant-garde",
      "ambient/chillout",
      "tribute_bands",
      "live_concert",
      "music_festival",
      "dj_set/club_night",
      "listening_session",
      "open_mic",
      "street_performance",
      "album_release/listening_party",
      "karaoke_night",
    ],
    vibe: [
      "chill_and_relaxed",
      "high-energy_and_loud",
      "intimate_and_acoustic",
      "party/dance",
    ],
    venue_type: [
      "stadium",
      "concert_hall",
      "club/lounge",
      "outdoor/park",
      "beach/boat_party",
      "rooftop",
    ],
  },

  arts_and_culture: {
    subcategories: [
      "theater/plays",
      "musicals",
      "ballet",
      "opera",
      "spoken_word/poetry",
      "classical_music_concerts",
      "art_exhibitions/gallery_openings",
      "film_screenings/short_films",
      "cultural_festivals",
      "literary_events/book_signings",
      "stand-up_comedy/improv",
      "circus/acrobatics",
      "puppetry/shadow_theater",
      "historical_reenactments",
      "traditional_dance_performances",
    ],
    vibe: [
      "refined_and_elegant",
      "creative_and_expressive",
      "intellectual_and_thought-provoking",
      "chill_and_social",
    ],
    venue_type: [
      "theater",
      "art_gallery",
      "museum",
      "cinema",
      "cultural_center",
      "outdoor_stage",
    ],
  },

  festivals: {
    subcategories: [
      "music_festivals",
      "food_and_drink_festivals",
      "wine/beer/spirits_tastings",
      "cultural/heritage_festivals",
      "film_festivals",
      "art_festivals",
      "fashion_festivals",
      "religious_festivals",
      "literature/book_festivals",
      "light/lantern_festivals",
      "street_festivals",
      "carnival/parade",
      "fireworks/pyro_festivals",
      "eco/sustainability_festivals",
      "technology/innovation_festivals",
      "lgbtq+_pride_events",
    ],
    vibe: [
      "vibrant_and_festive",
      "community_and_social",
      "cultural_and_traditional",
      "family-friendly",
      "nightlife_and_energetic",
    ],
    venue_type: [
      "outdoor/park",
      "street",
      "stadium",
      "waterfront",
      "exhibition_ground",
    ],
  },

  sports_and_fitness: {
    subcategories: [
      "football/soccer",
      "basketball",
      "volleyball",
      "baseball",
      "ice_hockey",
      "rugby",
      "cricket",
      "f1/motorsport",
      "tennis",
      "golf",
      "mma/boxing",
      "e-sports",
      "local_league_matches",
      "youth_sports",
      "friendly_games",
      "marathon",
      "half-marathon",
      "10k/5k_run",
      "trail_running",
      "obstacle_race",
      "triathlon",
      "cycling",
      "swimming",
      "rowing",
      "surfing",
      "sailing/yacht",
      "jet_ski",
      "yoga",
      "bootcamp",
      "zumba",
      "crossfit",
      "bodybuilding",
      "wellness_retreat",
      "climbing",
      "paragliding/skydiving",
      "paintball/laser_tag",
      "archery",
    ],
    vibe: [
      "competitive",
      "active_and_energetic",
      "fun_and_social",
      "wellness_and_mindful",
    ],
    venue_type: [
      "stadium",
      "sports_arena",
      "gym/studio",
      "outdoor_track",
      "beach",
      "mountain/trail",
      "waterfront",
    ],
  },
};

export const EVENT_CATEGORIES = [
  { label: "Music & Concerts", value: "music_and_concerts" },
  { label: "Arts & Culture", value: "arts_and_culture" },
  { label: "Festivals", value: "festivals" },
  { label: "Sports & Fitness", value: "sports_and_fitness" },
];

export const EVENT_SUB_CATEGORIES = {
  music_and_concerts: [
    { label: "Pop", value: "pop" },
    { label: "Rock", value: "rock" },
    { label: "Jazz", value: "jazz" },
    { label: "Blues", value: "blues" },
    { label: "Electronic / EDM", value: "electronic/edm" },
    { label: "Classical", value: "classical" },
    { label: "Hip-Hop / Rap", value: "hip_hop/rap" },
    { label: "R&B / Soul", value: "r&b/soul" },
    { label: "Country / Folk", value: "country/folk" },
    { label: "Reggae / Ska", value: "reggae/ska" },
    { label: "Indie / Alternative", value: "indie/alternative" },
    { label: "Metal / Punk", value: "metal/punk" },
    { label: "K-Pop / J-Pop", value: "k-pop/j-pop" },
    { label: "World / Ethnic", value: "world/ethnic" },
    { label: "Experimental / Avant-Garde", value: "experimental/avant-garde" },
    { label: "Ambient / Chillout", value: "ambient/chillout" },
    { label: "Tribute Bands", value: "tribute_bands" },
    { label: "Live Concert", value: "live_concert" },
    { label: "Music Festival", value: "music_festival" },
    { label: "DJ Set / Club Night", value: "dj_set/club_night" },
    { label: "Listening Session", value: "listening_session" },
    { label: "Open Mic", value: "open_mic" },
    { label: "Street Performance", value: "street_performance" },
    {
      label: "Album Release / Listening Party",
      value: "album_release/listening_party",
    },
    { label: "Karaoke Night", value: "karaoke_night" },
  ],

  arts_and_culture: [
    { label: "Theater / Plays", value: "theater/plays" },
    { label: "Musicals", value: "musicals" },
    { label: "Ballet", value: "ballet" },
    { label: "Opera", value: "opera" },
    { label: "Spoken Word / Poetry", value: "spoken_word/poetry" },
    { label: "Classical Music Concerts", value: "classical_music_concerts" },
    {
      label: "Art Exhibitions / Gallery Openings",
      value: "art_exhibitions/gallery_openings",
    },
    {
      label: "Film Screenings / Short Films",
      value: "film_screenings/short_films",
    },
    { label: "Cultural Festivals", value: "cultural_festivals" },
    {
      label: "Literary Events / Book Signings",
      value: "literary_events/book_signings",
    },
    { label: "Stand-Up Comedy / Improv", value: "stand-up_comedy/improv" },
    { label: "Circus / Acrobatics", value: "circus/acrobatics" },
    { label: "Puppetry / Shadow Theater", value: "puppetry/shadow_theater" },
    { label: "Historical Reenactments", value: "historical_reenactments" },
    {
      label: "Traditional Dance Performances",
      value: "traditional_dance_performances",
    },
  ],

  festivals: [
    { label: "Music Festivals", value: "music_festivals" },
    { label: "Food & Drink Festivals", value: "food_and_drink_festivals" },
    {
      label: "Wine / Beer / Spirits Tastings",
      value: "wine/beer/spirits_tastings",
    },
    {
      label: "Cultural / Heritage Festivals",
      value: "cultural/heritage_festivals",
    },
    { label: "Film Festivals", value: "film_festivals" },
    { label: "Art Festivals", value: "art_festivals" },
    { label: "Fashion Festivals", value: "fashion_festivals" },
    { label: "Religious Festivals", value: "religious_festivals" },
    {
      label: "Literature & Book Festivals",
      value: "literature/book_festivals",
    },
    { label: "Light / Lantern Festivals", value: "light/lantern_festivals" },
    { label: "Street Festivals", value: "street_festivals" },
    { label: "Carnival / Parade", value: "carnival/parade" },
    { label: "Fireworks / Pyro Festivals", value: "fireworks/pyro_festivals" },
    {
      label: "Eco / Sustainability Festivals",
      value: "eco/sustainability_festivals",
    },
    {
      label: "Technology / Innovation Festivals",
      value: "technology/innovation_festivals",
    },
    { label: "LGBTQ+ Pride Events", value: "lgbtq+_pride_events" },
  ],

  sports_and_fitness: [
    { label: "Football / Soccer", value: "football/soccer" },
    { label: "Basketball", value: "basketball" },
    { label: "Volleyball", value: "volleyball" },
    { label: "Baseball", value: "baseball" },
    { label: "Ice Hockey", value: "ice_hockey" },
    { label: "Rugby", value: "rugby" },
    { label: "Cricket", value: "cricket" },
    { label: "F1 / Motorsport", value: "f1/motorsport" },
    { label: "Tennis", value: "tennis" },
    { label: "Golf", value: "golf" },
    { label: "MMA / Boxing", value: "mma/boxing" },
    { label: "E-Sports", value: "e-sports" },
    { label: "Local League Matches", value: "local_league_matches" },
    { label: "Youth Sports", value: "youth_sports" },
    { label: "Friendly Games", value: "friendly_games" },
    { label: "Marathon", value: "marathon" },
    { label: "Half-Marathon", value: "half-marathon" },
    { label: "10K / 5K Run", value: "10k/5k_run" },
    { label: "Trail Running", value: "trail_running" },
    { label: "Obstacle Race", value: "obstacle_race" },
    { label: "Triathlon", value: "triathlon" },
    { label: "Cycling", value: "cycling" },
    { label: "Swimming", value: "swimming" },
    { label: "Rowing", value: "rowing" },
    { label: "Surfing", value: "surfing" },
    { label: "Sailing / Yacht", value: "sailing/yacht" },
    { label: "Jet Ski", value: "jet_ski" },
    { label: "Yoga", value: "yoga" },
    { label: "Bootcamp", value: "bootcamp" },
    { label: "Zumba", value: "zumba" },
    { label: "CrossFit", value: "crossfit" },
    { label: "Bodybuilding", value: "bodybuilding" },
    { label: "Wellness Retreat", value: "wellness_retreat" },
    { label: "Climbing", value: "climbing" },
    { label: "Paragliding / Skydiving", value: "paragliding/skydiving" },
    { label: "Paintball / Laser Tag", value: "paintball/laser_tag" },
    { label: "Archery", value: "archery" },
  ],
};

export const EVENT_VIBE = {
  music_and_concerts: [
    { label: "Chill & Relaxed", value: "chill_and_relaxed" },
    { label: "High-Energy & Loud", value: "high-energy_and_loud" },
    { label: "Intimate & Acoustic", value: "intimate_and_acoustic" },
    { label: "Party / Dance", value: "party/dance" },
  ],

  arts_and_culture: [
    { label: "Refined & Elegant", value: "refined_and_elegant" },
    { label: "Creative & Expressive", value: "creative_and_expressive" },
    {
      label: "Intellectual & Thought-Provoking",
      value: "intellectual_and_thought-provoking",
    },
    { label: "Chill & Social", value: "chill_and_social" },
  ],

  festivals: [
    { label: "Vibrant & Festive", value: "vibrant_and_festive" },
    { label: "Community & Social", value: "community_and_social" },
    { label: "Cultural & Traditional", value: "cultural_and_traditional" },
    { label: "Family-Friendly", value: "family-friendly" },
    { label: "Nightlife & Energetic", value: "nightlife_and_energetic" },
  ],

  sports_and_fitness: [
    { label: "Competitive", value: "competitive" },
    { label: "Active & Energetic", value: "active_and_energetic" },
    { label: "Fun & Social", value: "fun_and_social" },
    { label: "Wellness & Mindful", value: "wellness_and_mindful" },
  ],
};

export const EVENT_VENUE_TYPE = {
  music_and_concerts: [
    { label: "Stadium", value: "stadium" },
    { label: "Concert Hall", value: "concert_hall" },
    { label: "Club / Lounge", value: "club/lounge" },
    { label: "Outdoor / Park", value: "outdoor/park" },
    { label: "Beach / Boat Party", value: "beach/boat_party" },
    { label: "Rooftop", value: "rooftop" },
  ],

  arts_and_culture: [
    { label: "Theater", value: "theater" },
    { label: "Art Gallery", value: "art_gallery" },
    { label: "Museum", value: "museum" },
    { label: "Cinema", value: "cinema" },
    { label: "Cultural Center", value: "cultural_center" },
    { label: "Outdoor Stage", value: "outdoor_stage" },
  ],

  festivals: [
    { label: "Outdoor / Park", value: "outdoor/park" },
    { label: "Street", value: "street" },
    { label: "Stadium", value: "stadium" },
    { label: "Waterfront", value: "waterfront" },
    { label: "Exhibition Ground", value: "exhibition_ground" },
  ],

  sports_and_fitness: [
    { label: "Stadium", value: "stadium" },
    { label: "Sports Arena", value: "sports_arena" },
    { label: "Gym / Studio", value: "gym/studio" },
    { label: "Outdoor Track", value: "outdoor_track" },
    { label: "Beach", value: "beach" },
    { label: "Mountain / Trail", value: "mountain/trail" },
    { label: "Waterfront", value: "waterfront" },
  ],
};

export const EVENT_LOCATION_TYPES = [
  { label: "Within 10 km", value: "nearby" },
  { label: "Within city", value: "city" },
  { label: "Within country", value: "country" },
  { label: "Worldwide", value: "worldwide" },
];

export const EVENT_ENTRY_TYPES = [
  { label: "Free entry", value: "free" },
  { label: "Paid entry", value: "paid" },
];
