import { Avatar } from "@/components/common";
import { useAuth } from "@/components/providers/AuthProvider";
import { Feather, MaterialCommunityIcons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { Text, TouchableOpacity, View } from "react-native";

const VerifiedBadge = require("@/assets/images/icons/verified_badge.png");

interface EventDetailOverviewProps {
  eventType: "ai" | "user";
  hoster?: {
    _id: string;
    avatar: string;
    title: string;
    countryName: string;
    countryCode: string;
    is_verified: boolean;
  };
  description?: string;
  notes?: string;
}

const EventDetailOverview: React.FC<EventDetailOverviewProps> = ({
  eventType,
  hoster,
  description,
  notes,
}) => {
  const { user } = useAuth();
  const router = useRouter();

  return (
    <View className="flex-1 px-1">
      {/* HOSTER CARD - Glassmorphism Style */}
      <View className="">
        <Text className="font-dm-sans-bold text-[11px] uppercase tracking-[2px] text-slate-400 mb-3">
          Hosted By
        </Text>

        <TouchableOpacity
          activeOpacity={0.9}
          onPress={() =>
            hoster &&
            router.push({ pathname: "/profile", params: { id: hoster._id } })
          }
          disabled={!hoster}
          className="bg-slate-50/80 rounded-[24px] p-4 border border-slate-100 flex-row items-center justify-between shadow-sm shadow-slate-200"
        >
          {hoster ? (
            <View className="flex-row items-center gap-3">
              <Avatar source={hoster.avatar} name={hoster.title} size={40} />

              <View>
                <View className="flex flex-row items-center gap-2">
                  <Text className="font-poppins-bold text-slate-800 text-base">
                    {hoster.title}
                  </Text>
                  <MaterialCommunityIcons
                    name="check-decagram"
                    size={16}
                    color={hoster.is_verified ? "#16a34a" : "#cbd5e1"}
                  />
                </View>

                <Text className="font-dm-sans-bold text-slate-400 text-xs">
                  {hoster.countryName}
                </Text>
              </View>
            </View>
          ) : (
            <View className="flex-row items-center gap-3 py-1">
              <View className="w-12 h-12 rounded-full bg-slate-200 items-center justify-center">
                <MaterialCommunityIcons
                  name="robot-outline"
                  size={24}
                  color="#64748b"
                />
              </View>
              <Text className="font-dm-sans-bold text-slate-500 text-sm">
                {eventType === "ai"
                  ? "Generated by AI Engine"
                  : "Host information unavailable"}
              </Text>
            </View>
          )}

          {hoster && hoster._id !== user?._id && (
            <View className="bg-white w-10 h-10 rounded-full items-center justify-center border border-slate-100">
              <Feather name="chevron-right" size={20} color="#844AFF" />
            </View>
          )}
        </TouchableOpacity>
      </View>

      {/* ABOUT SECTION - Premium Typography */}
      <View className="rounded-[32px] border border-slate-50 py-4">
        <View className="flex-row items-center gap-2 mb-4">
          <LinearGradient
            colors={["#844AFF", "#C427E0"]}
            className="w-1 h-5 rounded-full"
          />
          <Text className="font-poppins-bold text-slate-900 text-base">
            About this event
          </Text>
        </View>

        {description || notes ? (
          <View className="gap-4">
            {description && (
              <Text className="font-dm-sans-medium text-sm text-slate-600">
                {description}
              </Text>
            )}

            {notes && (
              <View className="bg-purple-50/50 p-4 rounded-2xl border-l-4 border-purple-400">
                <Text className="font-dm-sans-bold text-[10px] text-purple-500 uppercase tracking-widest mb-1">
                  Host Notes
                </Text>
                <Text className="font-dm-sans-medium text-sm text-slate-700 italic">
                  "{notes}"
                </Text>
              </View>
            )}
          </View>
        ) : (
          <View className="py-10 items-center justify-center bg-slate-50/50 rounded-3xl border border-dashed border-slate-200">
            <MaterialCommunityIcons
              name="text-box-remove-outline"
              size={32}
              color="#cbd5e1"
            />
            <Text className="font-dm-sans-bold text-slate-400 text-sm mt-2">
              No description provided
            </Text>
          </View>
        )}
      </View>
    </View>
  );
};

export default EventDetailOverview;
