import { ITransferAvailability } from "@/types";
import { IEvent } from "@/types/data";

export const sampleTransfer: ITransferAvailability = {
  sessionId: "MWNlYzkwOTUyZjcyNDA4MGYzYzRhMTJjNTY3N2I3NWY=",
  searchResult: {
    originType: "IATA",
    originCode: "BLR",
    originName: "Bangalore (Bengaluru Intl. Airport) (BLR)",
    originProperty: "",
    originDetails: "flight",
    endType: "GIATA",
    endCode: "101249",
    endName: "Hyatt Bangalore MG Road",
    endProperty: "",
    endDetails: "accommodation",
    travelling: "2023-10-20T02:00:00",
    adults: "2",
    children: "0",
    infants: "0",
    resultCount: "35",
  },
  travelling: {
    products: [
      {
        general: {
          productId:
            "TRX-Y|4|D9EB6BEBD2AB4BE4A6115A20AF9FC5C220230726085657093",
          bookingTypeId: "TRX-26485596",
          transferTime: "56",
          productType: "Private MPV",
          productTypeId: "0",
          minPax: "",
          maxPax: "",
          perPerson: "0",
          luggage: "10",
          smallBagAllowance: "10",
          vehicleClass: "",
          vehicleMake: "",
          canxHours: "48",
          canxPerc: "100.00",
          canxOutOfHoursPP: "0",
          minStops: "0",
          maxStops: "0",
          numUnits: "2",
          supplierId: "2085",
          productSource: "1",
          supplierType: "0",
          companyLogo: "",
          vehicleImage:
            "https://www.hoppa.com/images/vehicle_images/ret2_suv.jpg",
          transferCompany: "TaxiBazaar",
          rating: "1.00",
          ratingClass: "1",
          numberOfReviews: "2",
          priceExpires: "60",
          description: "",
          isDeposit: "0",
          isCardPaymentAvailable: true,
        },
        pricing: {
          oldPrice: "12277.23",
          price: "12277.23",
          currency: "INR",
          carbonOffset: "0.00",
          transactionFees: {
            visa: "0.00",
            masterCard: "0.00",
            maestro: "0.00",
            visaDebit: "0.00",
            masterCardDebit: "0.00",
            amex: "0.00",
            payPal: "0.00",
          },
          prices: [
            {
              price: {
                type: "Vehicle",
                typeCode: "VEH",
                description: "Vehicle",
                units: "2",
                oldPrice: "12277.23",
                price: "12277.23",
                currency: "INR",
              },
            },
          ],
          extras: [
            {
              extra: {
                type: "Child seat",
                typeCode: "CHS",
                price: "0.00",
                currency: "INR",
              },
            },
            {
              extra: {
                type: "Booster seat",
                typeCode: "BAS",
                price: "0.00",
                currency: "INR",
              },
            },
          ],
        },
      },
    ],
  },
};

export const SAMPLE_EVENTS: IEvent[] = [
  {
    _id: "1",
    title: "Opener Festival Gdynia ",
    detail: "",
    country: "Portugal",
    country_code: "PT",
    region: "Lisboa",
    region_code: "LI",
    coordinate: {
      longitude: 0,
      latitude: 0,
    },
    address: "",
    opening_date: new Date(),
    end_date: new Date(),
    fee: { type: "free", currency: "usd", amount: 0 },
    preview_img:
      "https://cdn.prod.website-files.com/620b4dfc30add2618d5e13a5/622b57f4d6fe6adb2ed2c62c_ultimate-festival-planning-guide.jpeg",
  },
  {
    _id: "1",
    title: "Americian Top Ten",
    detail: "",
    country: "United Kingdom",
    country_code: "PT",
    region: "London",
    region_code: "LI",
    coordinate: {
      longitude: 0,
      latitude: 0,
    },
    address: "",
    opening_date: new Date(),
    end_date: new Date(),
    fee: { type: "free", currency: "usd", amount: 0 },
    preview_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVndedB6bALd6i4NLTbf045G71_969CkhUrnc0jsKqsRIhDKn19Fta1DPgy9y0Vox5w7I&usqp=CAU",
  },
  {
    _id: "1",
    title: "5 Skills every sport",
    detail: "",
    country: "Portugal",
    country_code: "PT",
    region: "Lisboa",
    region_code: "LI",
    coordinate: {
      longitude: 0,
      latitude: 0,
    },
    address: "",
    opening_date: new Date(),
    end_date: new Date(),
    fee: { type: "free", currency: "usd", amount: 0 },
    preview_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTquHt3RKzKZ5Kqz4aJPj7SikVq9EWMe7gk2ScDQNa-mu2pC8la4Y2KEvXXIL4QbwuN4AU&usqp=CAU",
  },
  {
    _id: "1",
    title: "Opener Festival Gdynia ",
    detail: "",
    country: "Portugal",
    country_code: "PT",
    region: "Lisboa",
    region_code: "LI",
    coordinate: {
      longitude: 0,
      latitude: 0,
    },
    address: "",
    opening_date: new Date(),
    end_date: new Date(),
    fee: { type: "free", currency: "usd", amount: 0 },
    preview_img:
      "https://cdn.prod.website-files.com/620b4dfc30add2618d5e13a5/622b57f4d6fe6adb2ed2c62c_ultimate-festival-planning-guide.jpeg",
  },
  {
    _id: "1",
    title: "Americian Top Ten",
    detail: "",
    country: "United Kingdom",
    country_code: "PT",
    region: "London",
    region_code: "LI",
    coordinate: {
      longitude: 0,
      latitude: 0,
    },
    address: "",
    opening_date: new Date(),
    end_date: new Date(),
    fee: { type: "free", currency: "usd", amount: 0 },
    preview_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVndedB6bALd6i4NLTbf045G71_969CkhUrnc0jsKqsRIhDKn19Fta1DPgy9y0Vox5w7I&usqp=CAU",
  },
  {
    _id: "1",
    title: "5 Skills every sport",
    detail: "",
    country: "Portugal",
    country_code: "PT",
    region: "Lisboa",
    region_code: "LI",
    coordinate: {
      longitude: 0,
      latitude: 0,
    },
    address: "",
    opening_date: new Date(),
    end_date: new Date(),
    fee: { type: "free", currency: "usd", amount: 0 },
    preview_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTquHt3RKzKZ5Kqz4aJPj7SikVq9EWMe7gk2ScDQNa-mu2pC8la4Y2KEvXXIL4QbwuN4AU&usqp=CAU",
  },
];
